### ISSUE TITLE
Group Capstone Project Kanban Board Set up

### ISSUE THREAD

**Issue by tan12082001** [tan12082001/react-group-capstone#25]
# Project Space Travelers' Hub Kanban Board set up

### Issue Information:

* The kanban board setup is done following the [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
* The Kanban board template used: [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1).
* Link to the Project created: [React-Capstone-Kanban-Board](https://github.com/tan12082001/react-group-capstone/projects/1).
* This Team includes: @tan12082001 and @Wils-FOURR-speed

**Comment by ridwanediallo** [comment]
# STATUS: APPROVED 🟢
## Hi 👋 @tan12082001 and @Wils-FOURR-speed , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Awesome job, team! 👏 You did a remarckable work creating the Kanban board. ✔
- The milestone requirements have been met with success. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
